version: "3.9"
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: six-cities_mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - six-cities_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: six-cities_mongo_express
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@db:27017/

volumes:
  six-cities_data:
